// <auto-generated />
namespace Capstone_HairSalon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class appointmentdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appointmentdated));
        
        string IMigrationMetadata.Id
        {
            get { return "201808152054408_appointmentdated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
